GET http://localhost:3000/posts

###
GET http://localhost:3000/posts/677aa9fa5bc8973b21a73f04

###
GET http://localhost:3000/posts?sender=KimK

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "content": "This is my secound post",
    "owner": "KimK",
    "username": "KimK",
    "userImgUrl": "https://media.theperfumeshop.com/medias/sys_master/prd-images/h99/he6/9189007589406/prd-front-1160142_420x420/paco-rabanne-olympea-eau-de-parfum-spray-420x420.jpg"
}

###
DELETE http://localhost:3000/posts/678ae068893651bf5f8afa72